#-------- General Settings --------
set -g mouse on
set-window-option -g mode-keys vi
set -g history-limit 12000
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

#-------- prefix key --------
unbind C-b
set -g prefix C-a
bind C-a send-prefix
# -------- Intuitive split screen keys --------
bind | split-window -h
bind - split-window -v

unbind '"'
unbind %

# -------- Better Pane-switching --------
bind h select-pane -L
bind l select-pane -R
bind k select-pane -U
bind j select-pane -D

#  Pane navigation vim style (zonder prefix)
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D

# -------- Status Bar --------
set -g status-interval 10
set -g status-left " #S "
set -g status-style "bg=#7aa2f7, fg=#0c1018"
# -------- Pane Borders  --------
set -g pane-border-style "fg=#3b4261" 
set -g pane-active-border-style "fg=#7aa2f7"
set -g pane-border-lines "double"

# -------- Achtergrond  --------
set -g window-style  "fg=colour102,bg=colour233"
set -g window-active-style "fg=#c0caf5,bg=#0f0f14"
# -------- Shortcuts -------
bind r source-file ~/.tmux.conf \; display "Tmux config herladen."
